### ISSUE TITLE
Timeout Error while loading /pull llava in the chatbar

### ISSUE THREAD

**Issue by Paramjethwa** [Leon-Sander/local_multimodal_ai_chat#33]
this is what i got in the streamlit app after 5 minutes of waiting after doing /pull llava

TimeoutError

Traceback:
File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
File "/app/app.py", line 171, in <module>
    main()
File "/app/app.py", line 123, in main
    response = command(user_input)
File "/app/utils.py", line 15, in command
    return pull_model_in_background(splitted_input[1])
File "/app/utils.py", line 73, in pull_model_in_background
    return asyncio.run(pull_ollama_model_async(model_name, stream=stream))
File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
File "/app/utils.py", line 39, in pull_ollama_model_async
    async with session.post(url, json=json_data) as response:
File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1353, in __aenter__
    self._resp = await self._coro
File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 684, in _request
    await resp.start(conn)
File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 994, in start
    with self._timer:
File "/usr/local/lib/python3.10/site-packages/aiohttp/helpers.py", line 713, in __exit__
    raise asyncio.TimeoutError from None

**Comment by Leon-Sander** [comment]
It seems that you solved the problems from the other two issues you created, can you write the solution under them please and close the issue?

For your issue, it seems to be an ollama related problem, so looking into their issues might help. Also how many pages does your pdf file have?

**Comment by Paramjethwa** [comment]
yes i have updated the solution for it

my pdf size was 1.5 mb only and when i try to /pull llava model it is showing processing and then timeout error.

/pull nomic-embed-text loads up pretty quick but the problem with that is when i upload an pdf file it is stuck on processing pdf... and now responsing anything even i ask in chatbar

**Comment by Leon-Sander** [comment]
I have updated the code yesterday to track timings, can you insert the pdf that is inside the pdf folder of this repository and then paste the command line output here so I can see whats happening and how long it takes?

**Comment by Paramjethwa** [comment]
ok so i did update the code with the latest commit you have done.

streamlit app.py in my browser, /pull nomic-embed-text 
upload the same pdf present in the repository( hover.pdf)

but still same issue of connectionerror : timeout 

This is what i got in my browser : 
[ERROR FILE 1.txt](https://github.com/user-attachments/files/17090476/ERROR.FILE.1.txt)

and this is what i got in my Ubuntu terminal : 
[ERROR FILE 2.txt](https://github.com/user-attachments/files/17090493/ERROR.FILE.2.txt)

**Comment by Leon-Sander** [comment]
In another issue you wrote that you changed the ollama url, did you also change it in the vectordb_handler.py file?

**Comment by Paramjethwa** [comment]
i have solved the timeout error and will upload the entire solution tomorrow in a proper format 

I've encountered a different issue where the /pull command for 'nomic-embed-text' completes successfully, and the PDF loads without any problems. However, 'nomic-embed-text' does not appear in the model selection section, while other random models I've pulled show up there, allowing me to choose them for chatting or asking questions about images.

Image for reference llava-phi3 is working fine for chat and image both
![image](https://github.com/user-attachments/assets/aa3c521f-d3e4-4aef-b994-84490b668e1a)

**Comment by Paramjethwa** [comment]
> In another issue you wrote that you changed the ollama url, did you also change it in the vectordb_handler.py file?
> 
> Also sidenote, you dont need to pull the same model over and over, after pulling it once, you have it locally. Also ollama did not recognize your gpu, make sure that you have the latest version of the code and wsl set up if you work on windows.

yes i did changed it in the vectordb file as well but now with the latest repo it works with ollama url too, yeah idky it is not recognizing the gpu

**Comment by Leon-Sander** [comment]
> However, 'nomic-embed-text' does not appear in the model selection section

I build a filter to not show models that have "embed" in their name, because you cant chat with embedding models, therefore it makes no sense to have them in the model selection. Also embeddings usually are chose once and then being used continuously. You can define which embedding model to use in the config.yml file

**Comment by Paramjethwa** [comment]
> > However, 'nomic-embed-text' does not appear in the model selection section
> 
> I build a filter to not show models that have "embed" in their name, because you cant chat with embedding models, therefore it makes no sense to have them in the model selection. Also embeddings usually are chosen once and then being used continuously. You can define which embedding model to use in the config.yaml file

oh okay make sense now so to summarize/chat with the pdf which model is being used after embedding the pdf?

**Comment by Leon-Sander** [comment]
Y you would need to delete it from the directory you defined, but its a but complicated since they are not named based on their model names.
The model used for the chat is the model you have chosen in the Select a Model dropdown.

**Comment by Leon-Sander** [comment]
Okay so I switched to windows and tested it out myself. Llama3.1 would not load on gpu for me, I also got a timeout error. But when loading smaller models it worked, but took a long time. For example 5 minutes to load llava on gpu while it took only 5 seconds on linux. Without gpu support it worked tho.

**Comment by Paramjethwa** [comment]
okay sure ill check out the ollama thread for solution for gpu usage 

also, once you upload the pdf using nomic embed text model, which model do you use to chat with pdf? 

also can you suggest similar kind of model such as llava but smaller in size so that we dont get a timeout error for it ?

**Comment by Leon-Sander** [comment]
You can choose what ever model you want for chatting. Look into the ollama library and select and try what fits your system best  https://ollama.com/library
For example 
gemma2:2b
qwen2.5:3b

**Comment by Paramjethwa** [comment]
AUDIO ERROR i am getting this when i record an audio from streamlitapp.

LibsndfileError: Error opening <_io.BytesIO object at 0x7f71cd288f40>: Format not recognised.

i feel like the audio which is recording is not in format of Wav or something similar acceptable format hence this error 

[Audioerror.txt](https://github.com/user-attachments/files/17101377/Audioerror.txt)

**Comment by Leon-Sander** [comment]
This seems to be another windows specific error, no problems on linux. I am investigating.

**Comment by Paramjethwa** [comment]
@Leon-Sander so i have tested the commit and at first the audio didnt work but later as i start the normal chat with keyboard and then used record audio it **Worked perfectly fine** 

And about **timeout Error** of /pull llava it still exist tried few time and end up with the same error of  asyncio.exceptions.TimeoutError
[ERROR FILE TIMEOUT ERROR.txt](https://github.com/user-attachments/files/17131680/ERROR.FILE.TIMEOUT.ERROR.txt)

**Comment by Leon-Sander** [comment]
Okay I think I got it now, it is an aiohttp error. I pushed a fix on a new branch, timout_error_fix. On line 53 in utils.py, you can set the time to wait, after which it will throw an timeout error, I set it to 30 minutes now. Can you please test if this fixes your problem, and adjust if you think you would need more time to download the model?

If this does not work, I got another workaround idea for you.

**Comment by Paramjethwa** [comment]
Hey Leon it took 15-20 minute to load the model and it got sucessfully completed this works perfectly fine now.. 
You are Amazing!! 
I aspire to become a skilled problem solver like you!

Now the chat App is successfully running everything, but the only issue here is ollama is not detecting/using my GPU to load or response query although i am trying to find the solution in ollama GitHub issue thread hope i find it soon.

**Comment by Leon-Sander** [comment]
Thanks happy to hear that.

Do you have wsl enabled in docker?

**Comment by Paramjethwa** [comment]
> Thanks happy to hear that.
> 
> Do you have wsl enabled in docker?

docker desktop was running completely fine but from the pas two days i am getting this issue of Docker desktop unexpectedly stopped and need to close 
![Screenshot 2024-09-26 190837](https://github.com/user-attachments/assets/e2610e70-5465-4014-a1de-9dcfa527136c)

i have reinstall and restarted the system 

also enable hyperV, WSL and virtualization through control panel but the same issue persist so iam trying to resolve this

**Comment by Paramjethwa** [comment]
> Thanks happy to hear that.
> 
> Do you have wsl enabled in docker?

I have enabled the WSL in docker desktop

**Comment by Paramjethwa** [comment]
Hi Leon finally found the solution for GPU usage, what i did it

1.  Re-install the docker complete and removed all the tmp.json files ( as there was multiple temporary file causing conflicts) from the .docker folder
2. Ran the docker desktop as an administrator.
3. Make sure the Cuda driver(nvcc --version) and NVidia Smi is responding perfectly
4. Checked and enable the WSL integration, also  
5. restarted the system 
6. rebuild the image: (docker compose up --Build)
7. Finally, it is recognizing the GPU and perfectly using while running the project

Major credit and thanks to you Leon for helping me solve every single problem super grateful!
